website/auth.py
from flask import Blueprint, render_template, request, session, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)


@auth.route("/signup/", methods=["POST", "GET"])
@login_required
def signup():
    from .models import create_staff
    if request.method == "POST":
        email = request.form.get("email").lower()
        password = request.form.get("password")
        type = request.form.get("type").capitalize()
        user = create_staff(email, password, department, type)
        if user:
            flash("Account created!", category="success")
        else:
            flash("Account creation failed!", category="failed")
        return redirect(url_for("auth.signup"))
    return render_template("signup.html", user=current_user)


@auth.route('/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route('/login/', methods=["POST", "GET"])
def login():   
    from .models import check_staff
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        user = check_staff(email, password)
        if user:
            login_user(user, remember=False)
            session.permanent = True
            return redirect(url_for("views.home"))
        else:
            flash("Incorrect password or email", category="failed")
    return render_template("login.html", user=current_user)


@auth.route("/")
def index(): #Check if user is logged in
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))
    return redirect(url_for("auth.login"))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required, current_user
from .models import StaffType

views = Blueprint('views', __name__)


@views.route('/home/')
@login_required
def home():
    return render_template(
        'home.html',
        user=current_user
    )

@views.route('/inventory/')
@login_required
def inventory():
    return render_template(
        'inventory.html',
        user=current_user
    )
    
@views.route('orders')
@login_required
def orders():
    return render_template(
        'orders.html',
        user=current_user
    )

@views.route('settings')
@login_required
def settings():
    return render_template(
        'settings.html',
        user=current_user
    )

website/templates/base.html
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link
		rel="stylesheet"
		href="{{ url_for('static', filename='css/base.css') }}"
	/>
	{% block links %}{% endblock %}
	<title>{% block title %}Loading{% endblock %}</title>
</head>
<body>
	{% with messages = get_flashed_messages(with_categories=true) %}
		{% if messages %}
			{% for category, message in messages %} 
                <div class="alert {{category}}" id="alert" role="alert">
                    {{ message }}
                    <button type="button" class="close-alert" onclick="closeAlert()" data-dismiss="alert">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
		{% endif %}
	{% endwith %}
{% block content %}{% endblock %}
<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
<script>
	function closeAlert() {
		var alert = document.getElementById("alert");
		if (alert != null) {
			alert.style.display = "none";
		}
	}
	function showAlert() {
		var alert = document.getElementById("alert");
		alert.style.display = "block";
	}
	setTimeout(closeAlert, 3000);
	
	function toggleContent(id) {
		var content = document.getElementById(id);
		if (content.style.display === "none" || content.style.display === "") {
			content.style.display = "block";
		} else {
			content.style.display = "none";
		}
	}
	
	function confirm_alert(message) {
		var result = confirm(message);
			if (result == false) {
				event.preventDefault();
			}
	}

</script>
{% block js %}{% endblock %}
</body>
</html>

website/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/home.css') }}"
/>
{% endblock %}

{% block content %}
{% include 'nav.html' %}
<h1>Home</h1>
<div class="content">
	<div class="child">
		<h2>Classes</h2>
		{% for i in range(10) %}
		<div class="expandable">
			<button type="checkbox" id="expandable-btn-{{ i+1 }}" onclick="toggleContent({{ i+1 }})">Class {{ i+1 }}</button>
			<div class="cls-content" id="{{ i+1 }}">
				<!-- PLACEHOLDER -->
				<h3>Test {{ i+1 }}</h3>
				<p>tabled content</p>
				<!-- END PLACEHOLDER -->
			</div>
		</div>
		{% endfor %}
	</div>
	<div class="child">
		<h2>Orders</h2>
	</div>
</div>
{% endblock %}

website/templates/inventory.html
{% extends 'base.html' %}
{% block title %}Inventory{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/home.css') }}"
/>
{% endblock %}
{% block content %}
{% include 'nav.html' %}

<h1>Inventory</h1>

{% endblock %}

website/templates/login.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/login.css') }}"
/>
{% endblock %}
<!-- No navigation content -->
{% block content %}
<main class="login-box">

	<h2>Sign In</h2>
	
	<form method="POST">

		<div class="input-field">
			<span class="icon"><ion-icon name="person"></ion-icon></span>
			<input type="email" name="email" id="email" autocomplete="on" required/>
			<label for="email">Email</label>
		</div>

		<div class="input-field">
			<span class="icon"><ion-icon name="lock-closed"></ion-icon></span>
			<input type="password" name="password" id="password" required/>
			<label for="password">Password</label>
		</div>
	
		<button type="submit" class="login-button">Login</button>
	
		<div class="terms-privacy">
			<p>By using our website, you agree to our <a href="#!">Terms & Privacy</a></p>
		</div>
	
	</form>
</main>
{% endblock %}

website/templates/nav.html
{% block links %}
<link
		rel="stylesheet"
		href="{{ url_for('static', filename='css/nav.css') }}"
/>
{% endblock %}
{% block content %}
{% if user.is_authenticated %}
<div class="nav-container">
	<button id="open-nav" onclick="toggleNav('open-nav')">
		<ion-icon name="menu-outline"/>
	</button>
	<div class="nav" id="nav">
		<button class="click" id="close-nav" onclick="toggleNav('close-nav')">
			<ion-icon name="close"/>
		</button>
		<button class="click" id="profile" onclick="toggleContent('logout')">
			<ion-icon name="person-circle"/>
		</button>
		<button class="click" id="logout">
			<a onclick="confirm_alert('You will be logged out')" href="{{ url_for('auth.logout') }}" close>
				<ion-icon name="log-out-outline"/>
			</a>
		</button>
		<button class="click" id="settings">
			<a href="{{ url_for('views.settings') }}">
				<ion-icon name="settings-outline"/>
			</a>
		</button>
		<ul>
			<li><a href="{{ url_for('views.home') }}">Home</a></li>
			<li><a href="{{ url_for('views.inventory') }}">Inventory</a></li>
			<li><a href="{{ url_for('views.orders') }}">Orders</a></li>
		</ul>
	</div>
</div>
{% endif %}
{% endblock %}
{% block js %}
<script>
	function toggleNav(id) {
		var nav = document.getElementById("nav");
		var icon = document.getElementById(id);
		if (nav.style.display === "none" || nav.style.display === "") {
			nav.style.display = "flex";
		} else {
			nav.style.display = "none";
		}
	}
	document.addEventListener('click', function(event) {
    var menu = document.getElementsByClassName('nav-container')[0];
	var nav = document.getElementById('nav');
    if (!menu.contains(event.target)) {
        nav.style.display = 'none';
    }
});
</script>
{% endblock %}

website/templates/orders.html
{% extends 'base.html' %}
{% block title %}Orders{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/home.css') }}"
/>
{% endblock %}
{% block content %}
{% include 'nav.html' %}

<h1>Orders</h1>

{% endblock %}

website/templates/settings.html
{% extends 'base.html' %}
{% block title %}Settings{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/home.css') }}"
/>
{% endblock %}
{% block content %}
{% include 'nav.html' %}

<h1>Settings</h1>

{% endblock %}

website/templates/signup.html
{% extends 'base.html' %}
{% block title %}Create Account{% endblock %}
{% block links %}
<link
	rel="stylesheet"
	href="{{ url_for('static', filename='css/login.css') }}"
/>
{% endblock %}
<!-- No navigation content -->
{% block content %}
<main class="login-box">

	<h2>Create an account</h2>
	
	<form method="POST">

		<div class="input-field">
			<input type="text" name="email" required/>
			<label for="email">Email</label>
		</div>

		<div class="input-field">
			<input type="password" name="password" required/>
			<label for="password">Password</label>
		</div>
		
		<div class="input-field">
			<input type="text" name="firstname" required/>
			<label for="firstname">Firstname</label>
		</div>
		
		<div class="input-field">
			<input type="text" name="surname" required/>
			<label for="surname">Surname</label>
		</div>
		
		<div class="input-field">
			<input type="text" name="type" required/>
			<label for="type">Type</label>
		</div>
	
		<button type="submit" class="login-button">Create Account</button>
	
	</form>
</main>
{% endblock %}